### ISSUE TITLE
json data not found

### ISSUE THREAD

**Issue by jegue** [AragurDEV/yowsup#16]
getting this erro today while try to send image or video

ERROR:yowsup.layers.protocol_media.mediauploader:Error occured at transfer json data not found
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.5.2-py3.4.egg/yowsup/layers/protocol_media/mediauploader.py", line 204, in run
    raise Exception("json data not found")
Exception: json data not found

**Comment by spt-shwetech** [comment]
me too. pls look up the error.

**Comment by galaxyitcenter** [comment]
same error getting

**Comment by pabloruan0710** [comment]
+1

**Comment by jegue** [comment]
[#20](https://github.com/AragurDEV/yowsup/pull/20)
