### ISSUE TITLE
live broadcast of location would crash program

### ISSUE THREAD

**Issue by Obeyed** [AragurDEV/yowsup#26]
On live broadcast of location this would continuously crash the app until the broadcast has finished.
See tgalal/yowsup#2251 for details.

In `yowsup/layers/protocol_notifications/layer.py` the method `recvNotification()` does not expect `location` type.

The first step would be to add the location type to the conditional and next is to maybe add logic for it?
Any thoughts on this?

**Comment by AragurDEV** [comment]
Yes, i'm not having lot's of time atm
Please report back with details or consider creating a pull request.
