### ISSUE TITLE
How to install yowsup on Centos 6

### ISSUE THREAD

**Issue by qvs5010** [AragurDEV/yowsup#51]
**first install debs**
```
yum -y install gcc gcc-c++ kernel-devel
yum -y install python-devel libxslt-devel libffi-devel openssl-devel
yum install ncurses-devel
yum install ImageMagick-devel
yum install readline
yum install sqlit
yum install sqlite-devel
```

**Second install python 3**
```
cd /tmp
wget https://www.python.org/ftp/python/3.6.4/Python-3.6.4.tar.xz
tar -xvf Python-3.6.4.tar.xz
 cd Python-3.6.4/
./configure
make && make install
```

**Third pip3 debs**
```
pip3 install  python-dateutil
pip3 install preview-generator
pip3 install protobuf
pip3 install pycrypto
pip3 install python-axolotl-curve25519
pip3 install python-axolotl
```

**forth install yowsup**
```
mkdir /var/whatsapp
cd var/whatsapp/
wget https://github.com/AragurDEV/yowsup/archive/master.zip
unzip master.zip
cd yowsup-master/
python3 setup.py install
```

##### check your --mcc -mnc @ https://en.wikipedia.org/wiki/Mobile_country_code
`python3 yowsup-cli registration --requestcode sms --phone ABCXXXXXXX --cc=ABC --mcc=XXX --mnc=XX`

##### Once run check the code that was sms'd to you
`python3 yowsup-cli registration --register SMSCODE --phone ABCXXXXXXX --cc ABC`

##### If all well you will see this, look for "pw: b'XXXXXXXXXXXXXXXX'" (remove b')
```
INFO:yowsup.common.http.warequest:b'{"status":"ok","login":"ABCXXXXXXX","type":"existing","pw":"XXXXXXXXXXXXXXXX","expiration":XXXXXXXXXXXXXXXX,"kind":"free","price":"$0.99","cost":"0.99","currency":"USD","price_expiration": XXXXXXX}\n'
status: b'ok'
login: b'ABCXXXXXXX'
price_expiration: XXXXXXX
pw: b'XXXXXXXXXXXXXXXX'
kind: b'free'
expiration: XXXXXXXXXXXXXXXX
currency: b'USD'
price: b'$0.99'
type: b'existing'
cost: b'0.99'
```

##### Then create a conf file

`vi config.whatsapp`

```
cc=ABC
phone=ABCXXXXXXX 
password=XXXXXXXXXXXXXXXX
```

##### To send 

`python3 yowsup-cli demos --send ABCXXXXXXX "Test message" --config config.whatsapp`

##### To Recvieve 

`python3 yowsup-cli demos --login ABCXXXXXXX:XXXXXXXXXXXXXXXX --echo -E s40`

I hope this helps!

**Comment by AragurDEV** [comment]
Closing because it's no existing issue. But thanks for your work.
