### ISSUE TITLE
Issue sending to Mexico and Argentina.  Is there something special about them?

### ISSUE THREAD

**Issue by hgc2002** [AragurDEV/yowsup#57]
I'v tried several phones from Mexico and Argentina, for sending messages to them.
Yowsup crash completely.
Does anyone had sent messages to these two countries?
Thanks for your help.

**Comment by AragurDEV** [comment]
Please attach logs

**Comment by hgc2002** [comment]
I found the issue. These two countries has special requirements for the phone numbers. For Mexico you have to add a "1" after the country code and for Argentina the same but with a "9".
Thanks for your time.
