### ISSUE TITLE
( Windows ) import magic: ImportError: failed to find libmagic.  Check your installation

### ISSUE THREAD

**Issue by mauriciofaria** [AragurDEV/yowsup#65]
I am unable to run a script on Windows.

Installed Python 3.4 from scratch and Yowsup as in README.md.

Tried to install ImageMagick as http://docs.wand-py.org/en/latest/guide/install.html#install-imagemagick-windows and nothing.

Installed libmagic with 

   pip install libmagic

and the result was

   Collecting libmagic
     Downloading libmagic-1.0.tar.gz
   Installing collected packages: libmagic
     Running setup.py install for libmagic ... done
   Successfully installed libmagic-1.0

if I try again

   Requirement already satisfied: libmagic in c:\python34\lib\site-packages

**Comment by AragurDEV** [comment]
Please follow the README https://github.com/AragurDEV/yowsup#windows
