### ISSUE TITLE
python3.2 No local packages  for requests

### ISSUE THREAD

**Issue by aero9** [AragurDEV/yowsup#82]
i'm trying to install requests package ... i get error when i do through python3
sudo python3 setup.py install

output
"SyntaxError: invalid syntax" 

AragurDEV script could not find the package ....i use 2 versions of python  and i have a local copy of requests in python  2.7.3 .

pip install requests
Requirement already satisfied: requests in

Processing dependencies for yowsup2==2.5.7
Searching for requests
Reading https://github.com/AragurDEV/python-axolotl/tarball/master
Reading http://pypi.python.org/simple/requests/
Couldn't find index page for 'requests' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading http://pypi.python.org/simple/
No local packages or download links found for requests
error: Could not find suitable distribution for Requirement.parse('requests')

i hope i asked related problem . my main point to send images/audio with yowsup

thanks

**Comment by AragurDEV** [comment]
Try ` pip3 install requests`

**Comment by aero9** [comment]
thanks aragur, i use old version of ubuntu 12.04 

 Command 'pip' from package 'python-pip' (universe)
pip3: command not found

**Comment by AragurDEV** [comment]
You have to install `python3-pip` because you we using Python 3

**Comment by aero9** [comment]
okay i will try and let you know .

regards

**Comment by AragurDEV** [comment]
So if you need any other support / assistance jump on our discord. https://discord.gg/Wa7QSxZ
I will close this issue for now.
