### ISSUE TITLE
can not register : no_routes

### ISSUE THREAD

**Issue by CoderJ** [AragurDEV/yowsup#9]
See your fork in https://github.com/tgalal/yowsup/issues/2261 and I clone your repo and try it. but it says "no_routes" when i request sms code

**Comment by AragurDEV** [comment]
Try using -e android

**Comment by mcaballeropinto** [comment]
I tried with "-E android" and I have the same problem.

**Comment by AragurDEV** [comment]
To troubleshoot this test pinging all WhatsApp servers

**Comment by fmachadodev** [comment]
Are you trying to activated your number using vpn?
this error occur when the Whatsapp can`t sent the message (or call)

**Comment by CoderJ** [comment]
I have do nothing, but it is ok now
